server:
  port: 9090
  
spring:
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: spring
 

mybatis: 
 mapper-locations: /mapper/**/*.xml
  
logging: 
 level: 
  root: info
  '[com.nb.spring]': debug