server:
  port: 9090
  
spring:
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@61.78.121.242:8877:xe
    username: nbif
    password: nbif
  mvc: 
    view: 
      suffix: .jsp
      prefix: /WEB-INF/views/

mybatis: 
 mapper-locations: /mapper/**/*.xml
  
logging: 
 level: 
  root: info
  '[com.nb.spring]': debug